### ISSUE TITLE
some query filter params not working

### ISSUE THREAD

**Issue by paultag** [openstates/billy#249]
subject is one that's seemingly broken?

cc/ @dcloud

**Comment by rshorey** [comment]
There seems to be a problem with session, too.

http://openstates.org/api/v1/bills/?state=tn&apikey=[apikey]&per_page=10&session=108

**Comment by dcloud** [comment]
Yes, subjects or subject or subject[], whatever it is. It is broken.

**Comment by dcloud** [comment]
See https://sunlight.atlassian.net/browse/DATA-389
