### ISSUE TITLE
Add `votes__id` query param for bills

### ISSUE THREAD

**Issue by paultag** [openstates/billy#262]
@rshorey @mileswwatkins - one of y'all - let's pair on this tomorrow.

**Comment by mileswwatkins** [comment]
Yup! I'm feeling pretty comfortable with Imago, so if @rshorey wants practice she can take it, or if she's busy I can make it happen.

**Comment by paultag** [comment]
(This is billy, not Imago :) )

**Comment by mileswwatkins** [comment]
:D

Well, definitely interested either way.

**Comment by rshorey** [comment]
me too, if it makes sense to do triad programming - otherwise I'm happy to let @mileswwatkins have all the fun

**Comment by paultag** [comment]
Sure, we'll make it work!

On Wed, Jul 15, 2015 at 3:58 PM, Rachel <notifications@github.com> wrote:

> me too, if it makes sense to do triad programming - otherwise I'm happy to
> let @mileswwatkins <https://github.com/mileswwatkins> have all the fun
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunlightlabs/billy/issues/262#issuecomment-121727904>.
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by jamesturk** [comment]
closing this out
