### ISSUE TITLE
Create CloudFormation template for billy-OS deployment?

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/billy#271]
Before we decommission Billy, it might be nice to create and release an AWS CloudFormation template of its resources. This would hit two goals, in my mind:

- help instruct others on how a Billy-based (or Billy-like) infrastructure could be deployed
- create a final snapshot of how the Billy system existed before we replace it (down the road) with OCD, for our own recollection, or in case anyone else wanted to run it

Also, it seems like a good thought experiment on deconstructing how the different servers interact, which could help us identify places to improve. (It'd also be good practice for me to learn how all the Billy AWS pieces fit together, frankly.)

**Comment by jamesturk** [comment]
going to close this, deployment repo documents this w/ ansible scripts as well as we're going to be able to
