### ISSUE TITLE
Division Boundary API failing

### ISSUE THREAD

**Issue by showerst** [openstates/billy#275]
I'm getting a piston API crash when I try to pull any district boundary URLs:

https://openstates.org/api/v1/districts/boundary/sldl/nc-120/?apikey=email@example.com

`Piston/0.2.3rc1 (Django 1.6.11) crash report: Traceback (most recent call last): File "/home/openstates/virt/local/lib/python2.7/site-packages/newrelic-2.76.0.55/newrelic/hooks/component_piston.py", line 33, in __call__ return self._nr_wrapped(*args, **kwargs) File "/home/openstates/virt2016-12-30-00-10/src/billy/billy/web/api/handlers.py", line 88, in new_read obj = old_read(*args, **kwargs) File "/home/openstates/virt2016-12-30-00-10/src/billy/billy/web/api/handlers.py", line 507, in read resp = rc.NOT_FOUND File "/home/openstates/virt2016-12-30-00-10/src/django-piston/piston/utils.py", line 55, in __getattr__ class HttpResponseWrapper(HttpResponse): File "/home/openstates/virt2016-12-30-00-10/src/django-piston/piston/utils.py", line 82, in HttpResponseWrapper content = property(HttpResponse._get_content, _set_content) AttributeError: type object 'HttpResponse' has no attribute '_get_content'`

**Comment by jamesturk** [comment]
that error is now a 404 and the correct boundary is now available at https://openstates.org/api/v1/districts/boundary/ocd-division/country%3Aus/state%3Anc/sldl%3A120/
