### ISSUE TITLE
Feature:  Allow NameMatcher._learn* to be extended

### ISSUE THREAD

**Issue by redNixon** [openstates/billy#276]
This is related to https://github.com/openstates/openstates/issues/1286 in openstates that required a manual aliases to be created.

The concerns about an "intelligent" name matcher mentioned in the issue are well placed, but I think a secondary system should still be looked into.  Manual intervention has to be used in some unavoidable cases, but situations that will create permanent admin overhead(in this case, always adding new mappings when shared last name officials are elected in MS) should be programmatically dealt with when possible.

Adding state specific name forms to Billy does not seem like the right approach.  As a state agnostic scraper, it should not have those type of rules in nor should it increase the size of the data sets for every state just to accommodate a single state usecase; this does not change the fact that some states could have naming conventions that conditionally apply to all members.  I am proposing that this change be considered:

Allow states within the openstates project a method to extend NameMatcher._learn* in some fashion for state specific naming conventions.  

Overall I think could help reduce the amount of maintenance work needed at the beginning of each session, give volunteers a way to directly address issues with the states that they are monitoring and improve data quality when mappings that fail are not reported.  However this could introduce new problems that might outweigh the benefits such as, openStates code could now create bad mappings that affect the Billy database and this new functionality could encourage bad practices when used outside of its scope(fixing accurately(but wrong) scraped names, one-off fixes, anything but formulaic mapping, etc).

If the broad notion of the change request is accepted, I'm not sure which way would be best to implement depending on what aspect of the code you think should be a priority:

Method 1:  Extend NameMatcher to inherit a StateLearn and BaseLearn class.
Instead of calling _learn* from NameMatcher.__init__() it would super the call to StateLearn and BaseLearn.  StateLearn would not have to contain a _learn* method but if it does it will have to also super a call to learn in order to get all potential name forms.  Something similar to this:

```
class BaseLearn(object):
    def _learn(self, data):
class StateLearn(BaseLearn):
    def _learn(self, data):
        super(StateLearn, self)._learn()
class NameMatcher(StateLearn, BaseLearn):
    def __init__(self, data):
        super(NameMatcher, self)._learn()
```
Pros:

- I personally find it cleaner than method 2 if that matters

- Any type of naming convention can be handled by the StateController as long as the data needed is contained in the legislator's name dictionary.  The odds of making changes to Billy in the future for state issues is lessened.

Cons:

- Every state will have to have a stubbed out StateLearn method unless hacky try/except code is added when StateLearn gets imported and falls back to a generic stub if it does not exist.  At best a new and potentially unused class is introduced to the Billy code, at worse every state __init__ contains a stub class that might not be used.  

- Removing the super call from StateLearn would cause the BaseLearn forms to not get added.  The odds of this method being misused seem greater than method 2.  Even though the Billy and openStates projects are closely tied together, code quality in one should not affect the other if possible.

Method 2:  Allow naming conventions to be specified in the State metadata.
This would entail creating a parser syntax for name forms, then dynamically creating new name forms from string based formulas contained in the metadata if they exist.

Pros

- No extra code/stubs have to be added to states that do not want to use this method

Cons

- Using the name syntax might not be intuitive for every volunteer which could introduce new bugs.

- New logic in Billy has to be created for whatever rule formatter get implemented.  This odds of creating new bugs using this method seems greater since method 1 does not introduce any largely different name form creation logic.

**Comment by jamesturk** [comment]
Hi Jon,

Thanks for the thoughtful input, I definitely see the value in an approach like this.  We're actually migrating away from billy to new infrastructure, and that'd be the time to reconsider our approach here.  I think the idea of per-state hooks in places like name matching do make sense.

Going to leave this open for now as a reminder, but will probably wind up being part of a different project.

**Comment by In-vincible** [comment]
@jamesturk I am almost done with pupa conversion of MS, I would like to know what I need to consider to solve this one, what are the things which were unresolved in billy version of MS?

**Comment by jamesturk** [comment]
This can wait, this is more about the name matching infrastructure than MS
specifically, but thanks for checking :+1:
